//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhSachPhim()
        {
            this.LichChieuPhims = new HashSet<LichChieuPhim>();
        }
    
        public int PhimId { get; set; }
        public string TenPhim { get; set; }
        public string DaoDien { get; set; }
        public string ThoiLuong { get; set; }
        public string XuatXu { get; set; }
        public string NoiDung { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieuPhim> LichChieuPhims { get; set; }
    }
}
