//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DanhSachPhim
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DanhSachPhim()
    {
        this.LichChieuPhims = new HashSet<LichChieuPhim>();
    }

    public int PhimId { get; set; }
    public string TenPhim { get; set; }
    public string DaoDien { get; set; }
    public string ThoiLuong { get; set; }
    public string XuatXu { get; set; }
    public string NoiDung { get; set; }
    public byte[] Image { get; set; }
    public string FilePath { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LichChieuPhim> LichChieuPhims { get; set; }
}

public partial class DanhSachPhongChieu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DanhSachPhongChieu()
    {
        this.LichChieuPhims = new HashSet<LichChieuPhim>();
    }

    public int PhongChieuId { get; set; }
    public string TenPhongChieu { get; set; }
    public int SoLuongGhe { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LichChieuPhim> LichChieuPhims { get; set; }
}

public partial class LichChieuPhim
{
    public int LichChieuId { get; set; }
    public int PhimId { get; set; }
    public int PhongChieuId { get; set; }

    public virtual DanhSachPhim DanhSachPhim { get; set; }
    public virtual DanhSachPhongChieu DanhSachPhongChieu { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
