//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrjDatabaseEntities : DbContext
    {
        public PrjDatabaseEntities()
            : base("name=PrjDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhSachPhim> DanhSachPhims { get; set; }
        public virtual DbSet<DanhSachPhongChieu> DanhSachPhongChieux { get; set; }
        public virtual DbSet<LichChieuPhim> LichChieuPhims { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
